services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pango
    networks:
      - pango-network
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.28.1
    depends_on:
      - postgresql
    environment:
      DB_PORT: 5432
      DB: postgres12
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      POSTGRES_PWD: secret
      POSTGRES_SEEDS: postgresql
      POSTGRES_USER: postgres
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    networks:
      - pango-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    restart: unless-stopped

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
    tty: true
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    networks:
      - pango-network
    stdin_open: true
    restart: unless-stopped
    
  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.34.0
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    networks:
      - pango-network
    ports:
      - 8233:8080
    restart: unless-stopped

networks:
  pango-network:
    driver: bridge
    name: pango-network