version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cccc
    ports:
      - 5432:5432
    restart: unless-stopped